name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up actions checkout 3
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set up MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: '5.0'
      - name: Set up chromedriver
        uses: nanasess/setup-chromedriver@v1
        with:
          chromedriver-version: '104.0.5112.79'
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - name: Compile
        run: mvn --batch-mode clean compile
      - name: Unit tests
        run: mvn --batch-mode test
      - name: Integration tests
        run: mvn --batch-mode verify "-Dskip.unit.tests=true"
      - name: Sonar
        run: mvn --batch-mode sonar:sonar "-Dsonar.login=${{ secrets.SONAR_LOGIN }}"