name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: '5.0'
      - uses: nanasess/setup-chromedriver@v1
        with:
          chromedriver-version: '104.0.5112.79'
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - name: Build with Maven
        run: mvn --batch-mode clean verify sonar:sonar "-Dsonar.login=${{ secrets.SONAR_LOGIN }}"